import type { Metadata } from "next";
import "./globals.css";
import AIAssistant from "@/components/AiAssistant";
import LanguageSwitcher from "../components/LanguageSwitcher"

// You can remove Geist if you're switching to Readex Pro only

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Fonts should go here */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Readex+Pro:wght@160..700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-readex">
        <AIAssistant/>
        {children}
        
        <LanguageSwitcher />  
      </body>
    </html>
  );
}

